apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo-simple

resources:
- kargo-simple-ns.yaml
- ghcr.io-creds.yaml
- stage-dev.yaml
- stage-staging.yaml
- stage-prod.yaml
