apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  annotations:
    kargo.akuity.io/color: red
spec:
  subscriptions:
    repos:
      images:
      - repoURL: ghcr.io/jessesuen/guestbook
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/jessesuen/kargo-simple.git
      writeBranch: master
      kustomize:
        images:
        - image: ghcr.io/jessesuen/guestbook
          path: env/dev
    argoCDAppUpdates:
    - appName: guestbook-simple-dev
