apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-simple
  namespace: guestbook-simple-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-simple
  template:
    metadata:
      labels:
        app: guestbook-simple
    spec:
      containers:
      - image: ghcr.io/jessesuen/guestbook:v0.0.22
        name: guestbook-simple
        ports:
        - containerPort: 3000
          name: http
