apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook-simple
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: guestbook-simple
    server: https://kubernetes.default.svc
  - name: '*'
    namespace: kargo-simple
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/jessesuen/kargo-simple.git
